flaskblog/main/routes.py
from flask import Blueprint, render_template, request
from flaskblog.Models.Post import Post
from flaskblog.forms.PostForm import Posts
from flask_login import login_required


main_page = Blueprint('main_page', __name__,template_folder='templates')


@main_page.route('/')
def index():
    return render_template('index.html', title='Home')


@main_page.route('/<string:username>/home')
@login_required
def home(username):
    page = request.args.get('page', 1, type=int)
    print("Page number= ", page)

    posts = Post.query.order_by(Post.publish_date.desc()).paginate(page=page, per_page=5)
    form = Posts()
    return render_template('home.html', posts=posts, title="Home")


@main_page.route('/about')
def about():
    return render_template('about.html', title="About")

flaskblog/posts/routes.py
from flask import Blueprint, redirect, url_for, request,flash, render_template, abort
from flaskblog import db
from flask_login import current_user, login_required
from flaskblog.forms.PostForm import Posts
from flaskblog.Models.Post import Post
from flaskblog.Models.User import User

posts = Blueprint('posts',__name__,template_folder='templates')


@posts.route('/<string:username>/new/post', methods=['GET', 'POST'])
@login_required
def new_post(username):
    form = Posts()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.post_field.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('You have added the post successfully', 'success')
        return redirect(url_for('main_page.home', username=current_user.username))

    return render_template('create_post.html', title='Create Post', form=form)


@posts.route('/<string:username>/posts', strict_slashes=False)
@posts.route('/<string:username>/post/<int:post_id>', strict_slashes=False)
@login_required
def post(username, post_id=None):
    if post_id:
        post = Post.query.get_or_404(post_id)
    else:
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=username).first_or_404()
        posts = Post.query.filter_by(user_id=user.id) \
            .order_by(Post.publish_date.desc()) \
            .paginate(page=page, per_page=10)
        return render_template('post.html', current_user=current_user, posts=posts)
    return render_template('post.html', current_user=current_user, post=post)


@posts.route('/<string:username>/edit/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def edit_post(post_id, username):
    post = Post.query.get_or_404(post_id)
    form = Posts()
    if username != current_user.username and post_id != post.id:
        abort(403)
    if form.validate_on_submit():
        post.body = form.post_field.data
        post.title = form.title.data
        db.session.commit()
        flash('Your post Edited Successfully!', 'success')
        return redirect(url_for('posts.post', post_id=post.id, username=post.author.username))
    elif request.method == 'GET':
        form.title.data = post.title
        form.post_field.data = post.body

    return render_template('create_post.html', title=post.title, post=post, form=form)


@posts.route('/delete-post/<int:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted successfully!!', 'success')
    return redirect(url_for('main_page.home', username=current_user.username))


@posts.route('/<string:username>/posts', methods=['GET'])
def user_posts(username):
    return redirect(url_for('posts.post', username=username))

flaskblog/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flaskblog import db
from flask_login import current_user, login_required, logout_user
from flaskblog.users.utils import save_iamge, updateUserInfo, new_password, send_reset_email
from flaskblog.forms.LoginForm import Login
from flaskblog.forms.RegistrationForm import Registration
from flaskblog.forms.UpdateProfileForm import UpdateProfileForm
from flaskblog.forms.ResetPasswordRequest import ResetPasswordRequest
from flaskblog.forms.ResetPassword import ResetPassword
from flaskblog.Models.User import User

users = Blueprint('users', __name__, template_folder='templates')


@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_page.home'))
    # creating an instance of the LoginForm to pass it to the view
    form = Login()
    if request.method == 'POST':
        if form.checkLoginValidity(form):
            next = request.args.get(
                'next')
            return redirect(url_for('main_page.home', username=current_user.username)) if next else redirect(
                url_for('main_page.index', username=current_user.username))
        else:
            flash(f"{form.email.data} and/or Password are incorrect. Please try again!", 'danger')

    return render_template('login.html', title="Login", form=form)


@users.route('/registration', methods=['GET', 'POST'])
def registration():
    # this issue is checking for the user if logged on or not and to customize the routes for the logged on user
    if current_user.is_authenticated:
        return redirect(url_for('main_page.home'))
    # creating an instance of the form to pass it to the view
    form = Registration()
    if request.method == "POST":
        if form.checkValidity(form):
            return redirect(url_for('users.login'))
        else:
            pass
    return render_template('registration.html', title="Registration", form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            current_user.image_file = save_iamge(form.picture.data)
            db.session.commit()
        updateUserInfo(form)
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.username.data = current_user.username
    image_file = url_for('static', filename='imgs/profile_pics/' + current_user.image_file)
    return render_template('profile.html', title=current_user.username + ' Profile', image_file=image_file,
                           current_user=current_user, form=form)


@users.route('/request-reset-password', methods=['POST', 'GET'])
def request_reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('users.profile'))
    form = ResetPasswordRequest()
    if form.validate_on_submit():
        if form.checkEmail(form.email.data):
            user = User.query.filter_by(email=form.email.data).first()
            send_reset_email(user)
            flash('An email with instruction to reset your password has been sent', 'info')
            return redirect(url_for('users.login'))
        else:
            pass
    return render_template('reset_password_request.html', form=form, title='Reset Password Request')


@users.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.profile'))
    user = User.verify_token(token)
    if user is None:
        flash("The requested token is invalid or expired", 'warning')
        return redirect(url_for('users.request_reset_password'))
    form = ResetPassword()
    new_password(form, user)
    return render_template('reset_password.html', form=form, title='Reset Password')

flaskblog/templates/layouts/_footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width= device-width, initial-scale:1, fit-to-shrink:no" name="viewport">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<footer>
    {% block footer %}
    <p>Waleed Saleh</p>
    <address>
        <p>Amman</p>
        <p>Jordan</p>
        <p>Phone Number: 454545452</p>
    </address>
    {% endblock %}
</footer>


</body>
</html>

flaskblog/templates/layouts/_headTag.html
<head>
    {% block head %}
        <meta charset="UTF-8">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link href="{{ url_for('static', filename='styles/css/main.css') }}" rel="stylesheet" type="text/css">
{#        <link rel="stylesheet" type="text/css" href="../../static/main.css">#}
        <meta content="width= device-width, initial-scale:1, fit-to-shrink:no" name="viewport">
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static',filename='styles/css/animate.min.css') }}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script crossorigin="anonymous"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script crossorigin="anonymous"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script crossorigin="anonymous"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% if title %}
            <title>Flask Blog - {{ title }}</title>
        {% else %}
            <title>Flask Blog</title>
        {% endif %}
    {% endblock %}
</head>

flaskblog/templates/layouts/_header.html
<!DOCTYPE html>
<html lang="en">
{% include 'layouts/_headTag.html' %}
<body>



</body>
</html>

flaskblog/templates/layouts/layout.html
<!DOCTYPE html>
<html lang="en">

{% include 'layouts/_headTag.html' %}

<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top ">
        <div class="container">
            {% if current_user.is_authenticated %}
                <a class="navbar-brand mr-4" href="{{ url_for('users.profile') }}">{{ current_user.username }} Blog</a>
            {% else %}
                <a class="navbar-brand mr-4" href="{{ url_for('main_page.index') }}">Blog</a>
            {% endif %}
            <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler"
                    data-target="#navbarToggle" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link"
                      href="{{ url_for('main_page.home', username=current_user.username.strip(' ')) }}">Home</a>
                    {% else %}
                    <a class="nav-item nav-link"
                      href="{{ url_for('main_page.index')}}">Home</a>
                    {% endif %}
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link"
                           href="{{ url_for('posts.new_post', username = current_user.username.strip(' ')) }}">New
                            Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.profile') }}">Profile</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.registration') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>


<main class="container" role="main" style="margin-top:70px;">
    {% block flash %}
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="container alert alert-{{ category }} col-sm-8 text-center">
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    {% endblock flash %}

    {% block main %}
        <div class="container">
            <div class="row">
                <div class="col">
                    {% block leftcontent %}
                    {% endblock leftcontent %}
                </div>
                <div class="col-8">
                    {% block content %}

                    {% endblock content %}
                </div>
                <div class="col">
                    {% block rightcontent %}
                    {% endblock rightcontent %}
                </div>
            </div>
        </div>
        </div>

        </main>
    {% endblock main %}
</body>
</html>