flaskblog/forms/LoginForm.py
from flaskblog import bcrypt
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email
from flaskblog.Models.User import User
from flask_login import login_user


class Login(FlaskForm):
    email = StringField('Username', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=30)])
    # We're gonna add a remember field to allow the user to stay login for a while after closing the browser using  secure cookies
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Login')


    def checkLoginValidity(self,form):
        user = User.query.filter_by(email=form.email.data).first()
        if form.validate_on_submit():
            if user and bcrypt.check_password_hash(user.password, form.password.data):
               login_user(user,remember=form.remember_me.data)
               return True
            else:
                return False

flaskblog/forms/PostForm.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField
from wtforms.validators import Length, DataRequired


class Posts(FlaskForm):
    post_field = TextAreaField("What's going on today ?", validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired(),Length(min=5)])
    submit = SubmitField('Post')

flaskblog/forms/RegistrationForm.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flaskblog import db
from flaskblog.Models.User import User


# importing the wtf_forms in order to make and validate the fields we want to use
# The stringField Represent the type of the field we want
# We pass the validator into a list
# importing the validator to validate the forms, by assigning the class we want to use.
# DataRequired specifies that the field can't be empty
# Length to assign the length of input
class Registration(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=6, max=30)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=30)])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), Length(min=6, max=30),
                                                 EqualTo('password')])
    submit = SubmitField('Sign Up')

    # ------------Validation Fields-----------------

    def checkValidity(self, form):
        if form.validate_on_submit():
           return True if self.saveUserToDatabase(form) else False

    def checkEmail(self, email):
        user = User.query.filter_by(email=email).first()
        if user:
            raise ValidationError("Email is taken, please try something else!")

    def checkUsername(self, username):
        user = User.query.filter_by(username=username).first()
        if user:
            raise ValidationError("Username is taken, please try something else!")

    def saveUserToDatabase(self, form):
        with db.session.no_autoflush:  # to avoid auto flush
            user = User(username=form.username.data, email=form.email.data)
            password = form.password.data
            username = form.username.data
            email = form.email.data
            user.setHashedPassword(password)
            db.session.add(user)
            username_query = User.query.filter_by(username=username).first()
            email_query = User.query.filter_by(email=email).first()
            try:
                if user.checkHashedPassword(password) and not username_query and not email_query:
                    db.session.commit()
                    flash(f"Account has been created, you can now login :) !", 'success')
                    return True
                else:
                    db.session.rollback()
                    flash("{} or {} already exist, Try another one!".format(username, email), 'info')
                    return False
            except Exception as e:
                raise ('Something went wrong through saving to database, ' + e)
            finally:
                db.session.close()

flaskblog/forms/ResetPassword.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField
from wtforms.validators import EqualTo, Length, DataRequired

class ResetPassword(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=50)])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(), Length(min=6, max= 50),EqualTo('password')])
    submit = SubmitField('Reset Password')

flaskblog/forms/ResetPasswordRequest.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email
from flaskblog.Models.User import User
from flask import flash


class ResetPasswordRequest(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Reset Password Request')

    def checkEmail(self, email):
        user = User.query.filter_by(email=email).first()
        return True if user else flash('Email is inccorrect please sing up to be able to reset your password!', 'warning')

flaskblog/posts/routes.py
from flask import Blueprint, redirect, url_for, request,flash, render_template, abort
from flaskblog import db
from flask_login import current_user, login_required
from flaskblog.forms.PostForm import Posts
from flaskblog.Models.Post import Post
from flaskblog.Models.User import User

posts = Blueprint('posts',__name__,template_folder='templates')


@posts.route('/<string:username>/new/post', methods=['GET', 'POST'])
@login_required
def new_post(username):
    form = Posts()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.post_field.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('You have added the post successfully', 'success')
        return redirect(url_for('main_page.home', username=current_user.username))

    return render_template('create_post.html', title='Create Post', form=form)


@posts.route('/<string:username>/posts', strict_slashes=False)
@posts.route('/<string:username>/post/<int:post_id>', strict_slashes=False)
@login_required
def post(username, post_id=None):
    if post_id:
        post = Post.query.get_or_404(post_id)
    else:
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=username).first_or_404()
        posts = Post.query.filter_by(user_id=user.id) \
            .order_by(Post.publish_date.desc()) \
            .paginate(page=page, per_page=10)
        return render_template('post.html', current_user=current_user, posts=posts)
    return render_template('post.html', current_user=current_user, post=post)


@posts.route('/<string:username>/edit/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def edit_post(post_id, username):
    post = Post.query.get_or_404(post_id)
    form = Posts()
    if username != current_user.username and post_id != post.id:
        abort(403)
    if form.validate_on_submit():
        post.body = form.post_field.data
        post.title = form.title.data
        db.session.commit()
        flash('Your post Edited Successfully!', 'success')
        return redirect(url_for('posts.post', post_id=post.id, username=post.author.username))
    elif request.method == 'GET':
        form.title.data = post.title
        form.post_field.data = post.body

    return render_template('create_post.html', title=post.title, post=post, form=form)


@posts.route('/delete-post/<int:post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted successfully!!', 'success')
    return redirect(url_for('main_page.home', username=current_user.username))


@posts.route('/<string:username>/posts', methods=['GET'])
def user_posts(username):
    return redirect(url_for('posts.post', username=username))

flaskblog/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flaskblog import db
from flask_login import current_user, login_required, logout_user
from flaskblog.users.utils import save_iamge, updateUserInfo, new_password, send_reset_email
from flaskblog.forms.LoginForm import Login
from flaskblog.forms.RegistrationForm import Registration
from flaskblog.forms.UpdateProfileForm import UpdateProfileForm
from flaskblog.forms.ResetPasswordRequest import ResetPasswordRequest
from flaskblog.forms.ResetPassword import ResetPassword
from flaskblog.Models.User import User

users = Blueprint('users', __name__, template_folder='templates')


@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_page.home'))
    # creating an instance of the LoginForm to pass it to the view
    form = Login()
    if request.method == 'POST':
        if form.checkLoginValidity(form):
            next = request.args.get(
                'next')
            return redirect(url_for('main_page.home', username=current_user.username)) if next else redirect(
                url_for('main_page.index', username=current_user.username))
        else:
            flash(f"{form.email.data} and/or Password are incorrect. Please try again!", 'danger')

    return render_template('login.html', title="Login", form=form)


@users.route('/registration', methods=['GET', 'POST'])
def registration():
    # this issue is checking for the user if logged on or not and to customize the routes for the logged on user
    if current_user.is_authenticated:
        return redirect(url_for('main_page.home'))
    # creating an instance of the form to pass it to the view
    form = Registration()
    if request.method == "POST":
        if form.checkValidity(form):
            return redirect(url_for('users.login'))
        else:
            pass
    return render_template('registration.html', title="Registration", form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            current_user.image_file = save_iamge(form.picture.data)
            db.session.commit()
        updateUserInfo(form)
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.username.data = current_user.username
    image_file = url_for('static', filename='imgs/profile_pics/' + current_user.image_file)
    return render_template('profile.html', title=current_user.username + ' Profile', image_file=image_file,
                           current_user=current_user, form=form)


@users.route('/request-reset-password', methods=['POST', 'GET'])
def request_reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('users.profile'))
    form = ResetPasswordRequest()
    if form.validate_on_submit():
        if form.checkEmail(form.email.data):
            user = User.query.filter_by(email=form.email.data).first()
            send_reset_email(user)
            flash('An email with instruction to reset your password has been sent', 'info')
            return redirect(url_for('users.login'))
        else:
            pass
    return render_template('reset_password_request.html', form=form, title='Reset Password Request')


@users.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.profile'))
    user = User.verify_token(token)
    if user is None:
        flash("The requested token is invalid or expired", 'warning')
        return redirect(url_for('users.request_reset_password'))
    form = ResetPassword()
    new_password(form, user)
    return render_template('reset_password.html', form=form, title='Reset Password')

flaskblog/templates/about.html
{% extends 'layouts/layout.html'%}


{% block content %}
   <h1 style="text-align: center">About Page</h1>
{% endblock content%}

flaskblog/templates/create_post.html
{% extends 'layouts/layout.html' %}
{% block main %}
    <div class="container border col-lg-11 p-3 waleed">
        <form method="POST" action="">
        {{ form.hidden_tag() }}
            <div class="form-group border-bottom-green">
                {% if form.title.errors %}
                {{ form.title(class='form-control is-invalid') }}
                {% for error in form.title.errors %}
                <div class="invalid-feedback">
                    <span class="text-danger">{{ error }}</span><br>
                </div>
                {% endfor %}
            {% else %}
                {{ form.title(class='form-control', placeholder='Title') }}
            {% endif %}
            </div>
            <div class="form-group">
                {% if form.post_field.errors %}
                {{ form.post_field(class='form-control is-invalid', cols= 10 , rows = 5) }}
                {% for error in form.post_field.errors %}
                <div class="invalid-feedback">
                    <span class="text-danger">{{ error }}</span><br>
                </div>
                {% endfor %}
            {% else %}
                {{ form.post_field(class='form-control',rows=2, placeholder ="What's on Your Mind ?") }}
            {% endif %}
            </div>
            {{ form.submit(class='btn btn-outline-info col-4') }}
        </form>
    </div>
{% endblock main%}

flaskblog/templates/home.html
{% extends 'layouts/layout.html' %}
{% block content %}

    {% if posts %}
        {% for post in posts.items %}
            <article class="media content-section mb-4" style="border-bottom-color:green ">
                <img class="rounded-circle article-img"
                     src="{{ url_for('static', filename='imgs/profile_pics/' + post.author.image_file) }}"
                     alt="User Profile Picture">
                <div class="media-body mt-3">
                    <div class="article-metadata mb-3 ">
                        <a class="mr-2" href="{{ url_for('posts.user_posts',username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted"> {{post.publish_date.strftime('%Y-%m-%d')}} </small>
                    </div>
                    {% if post.author == current_user %}
                        <h2><a class="article-title"
                               href="{{ url_for('posts.post', username = post.author.username, post_id = post.id) }}">{{ post.title }}</a>
                        </h2>
                    {% else %}
                        <h2 class="article-title">{{ post.title }}</h2>
                    {% endif %}
                    <p class="article-content mt-3">{{ post.body }}</p>
                    {% if post.author == current_user %}
                        <div class="border-top">
                            <a class="btn btn-secondary mt-2"
                               href="{{ url_for('posts.edit_post',post_id = post.id, username = post.author.username) }}">
                                Edit
                            </a>
                            <button type="button" class="btn btn-danger mt-2" data-toggle="modal"
                                    data-target="#deletePost">
                                Delete
                            </button>
                        </div>
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="deletePost" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleatableModal">Delete Post</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                        </button>
                                        <form method="POST"
                                              action="{{ url_for('posts.delete_post', post_id = post.id) }}">
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
            </article>
        {% endfor %}
        <div class="pagination " style="margin-left: 20px;">
            {%- for page in posts.iter_pages(left_edge=2, left_current= 1, right_edge = 2, right_current = 1) %}
                {% if page %}
                    {% if page != posts.page %}
                        <a class="btn btn-outline-info m-1 "
                           href="{{ url_for('main_page.home',username = current_user.username ,page=page) }}">{{ page }}</a>
                    {% else %}
                        <a class="btn btn-info"
                           href="{{ url_for('main_page.home',username = current_user.username ,page = page) }}">{{ page }}</a>
                    {% endif %}
                {% else %}
                    <span class="ellipsis">…</span>
                {% endif %}
            {%- endfor %}
        </div>
    {% else %}
        <h1 class="toast-header text-center">{{ current_user.username }} HAS NO POSTS YET !</h1>
    {% endif %}

{% endblock %}

flaskblog/templates/index.html
{% extends 'layouts/layout.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 50px">
        <h1 class="animated flash text-center">Welcome To Our BLOG</h1>
    </div>
{% endblock %}

flaskblog/templates/login.html
{% extends 'layouts/layout.html' %}

{% block content %}
{{ form.hidden_tag() }}
    <div class="content-section align-content-center">
        <form method="POST" action="">
        {{ form.hidden_tag() }}
         {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        {% for error in form.email.errors %}
                            <div class="invalid-feedback">
                                <span>{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                <span>{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}
                </div>
                <div>
                    <div class="form-check d-flex">
                        {{ form.remember_me(class="form-check-input") }}
                        {{ form.remember_me.label(class="form-check-label") }}
                    </div>
                    {{ form.submit(class="btn btn-outline-info") }}
                    <small class="text-muted ml-2 ">
                        <a href="{{url_for('users.request_reset_password')}}" >Forgot your password?</a>
                    </small>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="border-top">
        <small class="text-muted ml-2">
            Need an account? <a href="{{ url_for('users.registration') }}">Sign Up</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends 'layouts/layout.html' %}

{% block main %}
    {% if posts %}
        {% for post in posts.items %}
            <article class="media content-section mb-4" style="border-bottom-color:green ">
                <img class="rounded-circle article-img"
                     src="{{ url_for('static', filename='imgs/profile_pics/' + post.author.image_file) }}"
                     alt="User Profile Picture">
                <div class="media-body mt-3">
                    <div class="article-metadata mb-3 ">
                        <a class="mr-2 " href="#">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.publish_date.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <h2><p class="article-title">{{ post.title }}</p></h2>
                    <p class="article-content ">{{ post.body }}</p>
                </div>
            </article>
        {% endfor %}
    {% elif post %}
        <article class="media content-section mb-4" style="border-bottom-color:green ">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='imgs/profile_pics/' + post.author.image_file) }}"
                 alt="User Profile Picture">
            <div class="media-body mt-3">
                <div class="article-metadata mb-3 ">
                    <a class="mr-2 " href="#">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.publish_date.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><p class="article-title">{{ post.title }}</p></h2>
                <p class="article-content ">{{ post.body }}</p>
            </div>
        </article>
    {% endif %}
{% endblock main %}

flaskblog/templates/profile.html
{% extends 'layouts/layout.html' %}

{% block content %}

    <div class="content-section ">
        <div class="media">
            <img class="rounded-circle profile-img" src="{{ image_file }}" alt="Profile Picture">
            <div class="media-body">
                <h2 class="profile-heading">Username</h2>
                <p class="text-secondary">{{ current_user.username }}</p>
                <h2 class="profile-heading">Email</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <button class="btn btn-outline-info" type="button" data-toggle="collapse"
                data-target="#edit-collapse" aria-expanded="false" id="edit-info" aria-controls="edit-collapse">
            Edit Info
        </button>
        <div class="collapse mt-2" id="edit-collapse">
            <form method="POST" action="" enctype="multipart/form-data">
                <fieldset class="form-group mt-3">
                    <legend class="border-bottom">Edit</legend>
                    {{ form.csrf_token }}
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.email.label(class='form-control-label') }}
                        {% if form.email.errors %}
                            {{ form.email(class='form-control is-invalid') }}
                            {% for error in form.email.errors %}
                                <div class="invalid-feedback">
                                    <span>{{ error }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ form.email(class='form-control') }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.username.label(class='form-control-label') }}
                        {% if form.username.errors %}
                            {{ form.username(class='form-control is-invalid') }}
                            {% for error in form.username.errors %}
                                <div class="invalid-feedback">
                                    <span>{{ error }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ form.username(class='form-control') }}
                        {% endif %}
                    </div>
                <div class="form-group">
                    {{ form.picture.label(class='form-control-label') }}
                    <br>
                    {{ form.picture(class='mb-2') }}
                <br>
                    {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger mb-2">{{ error }}</span><br>
                    {% endfor %}
                {% endif %}
                <div>
                </div>
                    {{ form.submit(class='btn btn-outline-info') }}
                </fieldset>
            </form>
        </div>
    </div>

{% endblock content %}

flaskblog/templates/registration.html
{% extends 'layouts/layout.html' %}


{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">JOIN US BUDDIES</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password(class="form-control") }}
                {% endif %}
            </div>
            {{ form.submit(class="btn btn-outline-info") }}
        </fieldset>
    </form>
</div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have an Account ? <a href="{{ url_for('users.login') }}">Login</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/reset_password.html
{% extends 'layouts/layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control is-invalid') }}
                        {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                <span class="text-danger">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% else %}
                        {{ form.password(class='form-control')}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class='form-control-label') }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class='form-control is-invalid') }}
                        {% for error in form.confirm_password.errors %}
                            <div class="invalid-feedback">
                                <span class="text-danger">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% else %}
                        {{ form.confirm_password(class='form-control')}}
                    {% endif %}
                </div>
                {{ form.submit(class='btn btn-outline-info')}}
            </fieldset>
        </form>
    </div>
{% endblock %}